/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package experimento;

import experimento.Animal;
import experimento.Leon;
import experimento.Mono;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Andrés
 */
public class ZoologicoGUI extends javax.swing.JFrame {

    private JFrame ventana;
    private JTextField txtAnimal;
    private JTextArea txtResultado;
    /**
     * Creates new form ventana
     */
    public ZoologicoGUI() {
        initComponents();
        ventana = new JFrame("Zoológico");
        ventana.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ventana.setLayout(new FlowLayout());

        // Panel central con JTextField y botones
        JPanel panelCentral = new JPanel();
        panelCentral.setLayout(new BorderLayout());

        JPanel panelSuperior = new JPanel();
        panelSuperior.setLayout(new BoxLayout(panelSuperior,BoxLayout.Y_AXIS));
        
        JLabel lblBienvenida = new JLabel("Bienvenido al Zoológico!");
        lblBienvenida.setAlignmentX(Component.CENTER_ALIGNMENT);
        panelSuperior.add(lblBienvenida);
        panelSuperior.add(Box.createVerticalStrut(20));
        
        
        JLabel lblInstruccion = new JLabel("Ingrese el nombre del animal que desea gestionar:");
        lblInstruccion.setAlignmentX(Component.CENTER_ALIGNMENT);
        panelSuperior.add(lblInstruccion);
        panelSuperior.add(Box.createVerticalStrut(10));
        
        txtAnimal = new JTextField(20);
        txtAnimal.setAlignmentX(Component.CENTER_ALIGNMENT);
        panelSuperior.add(txtAnimal);
        panelCentral.add(panelSuperior, BorderLayout.NORTH);

        // Panel inferior con botones
        JPanel panelInferior = new JPanel();
        panelInferior.setLayout(new FlowLayout(FlowLayout.CENTER, 20, 20));
        JButton btnComer = new JButton("Comer");
        btnComer.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        Animal animal = crearAnimal(txtAnimal.getText());
        if (animal != null) {
            txtResultado.setText(animal.comer());
        } else {
            txtResultado.setText("Animal no encontrado");
        }
    }
});
panelInferior.add(btnComer);

JButton btnDormir = new JButton("Dormir");
btnDormir.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        Animal animal = crearAnimal(txtAnimal.getText());
        if (animal != null) {
            txtResultado.setText(animal.dormir());
        } else {
            txtResultado.setText("Animal no encontrado");
        }
    }
});
panelInferior.add(btnDormir);

JButton btnHacerRuido = new JButton("Hacer Ruido");
btnHacerRuido.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        Animal animal = crearAnimal(txtAnimal.getText());
        if (animal != null) {
            txtResultado.setText(animal.hacerRuido());
        } else {
            txtResultado.setText("Animal no encontrado");
        }
    }
});
        panelInferior.add(btnHacerRuido);
        panelCentral.add(panelInferior, BorderLayout.CENTER);

        ventana.add(panelCentral, BorderLayout.CENTER);

        // Panel inferior con JTextArea no editable
        JPanel panelResultado = new JPanel();
        panelResultado.setLayout(new BorderLayout());
        txtResultado = new JTextArea(10, 20);
        txtResultado.setEditable(false);
        panelResultado.add(new JScrollPane(txtResultado), BorderLayout.CENTER);
        panelCentral.add(panelResultado, BorderLayout.SOUTH);
        

        ventana.pack();
        ventana.setLocationRelativeTo(null); // Centrar la ventana en la pantalla
        ventana.setVisible(true);
    }

    private Animal crearAnimal(String nombre) {
        if (nombre.equalsIgnoreCase("León")) {
            return new Leon();
        } else if (nombre.equalsIgnoreCase("Mono")) {
            return new Mono();
        } else {
            return null;
        }
    }
    public static void main(String[] args) {
        new ZoologicoGUI();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
